# Generated by Django 5.2.4 on 2025-08-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBusinessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, verbose_name='No.')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('january', models.CharField(blank=True, max_length=100)),
                ('february', models.CharField(blank=True, max_length=100)),
                ('march', models.CharField(blank=True, max_length=100)),
                ('april', models.CharField(blank=True, max_length=100)),
                ('may', models.CharField(blank=True, max_length=100)),
                ('june', models.CharField(blank=True, max_length=100)),
                ('july', models.CharField(blank=True, max_length=100)),
                ('august', models.CharField(blank=True, max_length=100)),
                ('september', models.CharField(blank=True, max_length=100)),
                ('october', models.CharField(blank=True, max_length=100)),
                ('november', models.CharField(blank=True, max_length=100)),
                ('december', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TracerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=50, verbose_name='No.')),
                ('establishment', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('business', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('first', models.CharField(blank=True, max_length=100, verbose_name='1st')),
                ('date2', models.CharField(blank=True, max_length=100)),
                ('second', models.CharField(blank=True, max_length=100, verbose_name='2nd')),
                ('date3', models.CharField(blank=True, max_length=100)),
                ('third', models.CharField(blank=True, max_length=100, verbose_name='3rd')),
                ('final', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
