# Generated by Django 5.2.4 on 2025-08-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='april',
            field=models.CharField(blank=True, max_length=100, verbose_name='April'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='august',
            field=models.CharField(blank=True, max_length=100, verbose_name='August'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='december',
            field=models.CharField(blank=True, max_length=100, verbose_name='December'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='february',
            field=models.CharField(blank=True, max_length=100, verbose_name='February'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='january',
            field=models.CharField(blank=True, max_length=100, verbose_name='January'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='july',
            field=models.CharField(blank=True, max_length=100, verbose_name='July'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='june',
            field=models.CharField(blank=True, max_length=100, verbose_name='June'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='march',
            field=models.CharField(blank=True, max_length=100, verbose_name='March'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='may',
            field=models.CharField(blank=True, max_length=100, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='november',
            field=models.CharField(blank=True, max_length=100, verbose_name='November'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='october',
            field=models.CharField(blank=True, max_length=100, verbose_name='October'),
        ),
        migrations.AlterField(
            model_name='monthlybusinessrecord',
            name='september',
            field=models.CharField(blank=True, max_length=100, verbose_name='September'),
        ),
        migrations.AlterField(
            model_name='tracerrecord',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='tracerrecord',
            name='business',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business'),
        ),
        migrations.AlterField(
            model_name='tracerrecord',
            name='date',
            field=models.CharField(blank=True, max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tracerrecord',
            name='date2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Date2'),
        ),
        migrations.AlterField(
            model_name='tracerrecord',
            name='date3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Date3'),
        ),
        migrations.AlterField(
            model_name='tracerrecord',
            name='establishment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Establishment'),
        ),
        migrations.AlterField(
            model_name='tracerrecord',
            name='final',
            field=models.CharField(blank=True, max_length=100, verbose_name='Final'),
        ),
        migrations.AlterField(
            model_name='tracerrecord',
            name='owner',
            field=models.CharField(blank=True, max_length=255, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='tracerrecord',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterModelTable(
            name='monthlybusinessrecord',
            table='Monthly_business_records',
        ),
        migrations.AlterModelTable(
            name='tracerrecord',
            table='Tracer_records',
        ),
    ]
