# Generated by Django 5.2.4 on 2025-08-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_alter_monthlybusinessrecord_address_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tracerrecord',
            table='tracer_records',
        ),
    ]
