# Generated by Django 5.2.4 on 2025-08-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_alter_tracerrecord_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyBusinessRecord',
        ),
    ]
