# Generated by Django 5.2.4 on 2025-08-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_delete_monthlybusinessrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracerrecord',
            name='datefinal',
            field=models.CharField(blank=True, max_length=100, verbose_name='DateFinal'),
        ),
    ]
