# Generated by Django 5.2.4 on 2025-08-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_barangay'),
        ('ocr', '0007_load_barangays'),
    ]

    operations = [
    ]
